[package]
name = "bake"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
colored = "2.1.0"
duct = "0.13.7"
tokio = { version = "1.39.2", features = ["io-util", "process"] }
